arts_entertainment: [entertainment, arts]
business: [business]
computer_internet: [technology]
science_technology: [technology]
culture_politics: [politics]
gaming: [games]
health: [health]
law_crime: [politics]
religion: [politics]
recreation: [sports, hobbies]
sports: [sports]
weather:  [places]
