package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  flash_socket:
    - public/javascripts/vendor/FABridge.js
    - public/javascripts/vendor/swfobject.js
    - public/javascripts/vendor/web_socket.js
  jquery:
    - public/javascripts/redmond/js/jquery-1.5.1.min.js
  actwittyall:
    - public/javascripts/rails.js
    - public/javascripts/redmond/js/jquery-ui-1.8.13.custom.min.js
    - public/javascripts/actwitty/application.js
    - public/javascripts/plugins/ui-watermark/ui.watermark.js
    - public/javascripts/plugins/jquery_ujs.js
    - public/javascripts/rails.validations.js
    - public/javascripts/rails.validations.custom.js
    - public/javascripts/cal.js
  profile:
    - public/javascripts/actwitty/aw_slider.js
    - public/javascripts/plugins/jquery-list-splitter/jquery.easyListSplitter.js
    - public/javascripts/actwitty/profile_filter.js
    - public/javascripts/actwitty/profile_channels.js
    - public/javascripts/actwitty/profile_locations.js
    - public/javascripts/actwitty/profile_things.js
    - public/javascripts/actwitty/profile_followers.js
    - public/javascripts/actwitty/profile_facebook.js
    - public/javascripts/actwitty/profile_followings.js
    - public/javascripts/actwitty/profile_follow.js
    - public/javascripts/actwitty/profile_summary.js
    - public/javascripts/actwitty/profile_stream.js
    - public/javascripts/actwitty/profile.js
    - public/javascripts/actwitty/profile_modals.js
    - public/javascripts/actwitty/profile_people.js
    - public/javascripts/plugins/jquery-autocomplete/lib/jquery.bgiframe.min.js
    - public/javascripts/plugins/jquery-autocomplete/lib/jquery.ajaxQueue.js
    - public/javascripts/plugins/jquery-autocomplete/lib/thickbox-compressed.js
    - public/javascripts/plugins/jquery-autocomplete/jquery.autocomplete.js
  jquery_devel:
    - public/javascripts/rails.js
    - public/javascripts/redmond/js/jquery-1.5.1.min.js
    - public/javascripts/redmond/js/jquery-ui-1.8.13.custom.min.js
    - public/javascripts/redmond/development-bundle/external/jquery.metadata.js
    - public/javascripts/actwitty/getting_in.js
    - public/javascripts/redmond/development-bundle/ui/minified/jquery.ui.core.min.js
    - public/javascripts/redmond/development-bundle/ui/minified/jquery.ui.widget.min.js
    - public/javascripts/redmond/development-bundle/ui/minified/jquery.ui.button.min.js
    - public/javascripts/redmond/development-bundle/ui/minified/jquery.ui.dialog.min.js
    - public/javascripts/plugins/ui-watermark/ui.watermark.js
    - public/javascripts/rails.validations.js
    - public/javascripts/rails.validations.custom.js
    - public/javascripts/plugins/profile_view.js
    - public/javascripts/cal.js
    - public/javascripts/jquery.nivo.slider.pack.js
    - public/javascripts/actwitty/jquery-placeholder-0.1.js
    - public/javascripts/actwitty/jquery.placeholder.js
    - public/javascripts/actwitty/placeholder.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/vendor/jqueryui.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/jquery.hotkeys.js
    - public/javascripts/vendor/jquery.autoresize.min.js
    - public/javascripts/vendor/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
  mobile:
    - public/javascripts/vendor/jquery152.min.js
    - public/javascripts/vendor/jquery.mobile-1.0a4.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/rails.js
  mailchimp:
    - public/javascripts/vendor/mailchimp/jquery.form.js
    - public/javascripts/vendor/mailchimp/jquery.validate.js
    - public/javascripts/vendor/mailchimp/jquery126.min.js



stylesheets:
  defaults:
    - public/stylesheets/actwitty/signin.css
    - public/stylesheets/actwitty/about.css
    - public/stylesheets/actwitty/profile.css
    - public/stylesheets/actwitty/validations.css
    - public/stylesheets/actwitty/simple_form.css
    - public/stylesheets/actwitty/image_scroll.css
    - public/stylesheets/actwitty/home_page.css
    - public/stylesheets/plugins/jquery-autocomplete/jquery.autocomplete.css
    - public/stylesheets/redmond/css/redmond/jquery-ui-1.8.13.custom.css
    - public/stylesheets/actwitty/mainpage.css


