package_assets: on 
embed_assets: datauri
compress_assets: off
gzip_assets: off
javascripts:
  flash_socket:
    - public/javascripts/vendor/FABridge.js
    - public/javascripts/vendor/swfobject.js
    - public/javascripts/vendor/web_socket.js
  jquery:
    - public/javascripts/jquery/jquery-1.6.2.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
  actwittyall:
    - public/javascripts/jquery/jquery-ui-1.8.14/ui/minified/jquery-ui.min.js
    - public/javascripts/actwitty/main_page.js
    - public/javascripts/plugins/ui-watermark/ui.watermark.js
    - public/javascripts/plugins/jquery_ujs.js
    - public/javascripts/plugins/rails.validations.js
    - public/javascripts/plugins/rails.validations.custom.js
    - public/javascripts/cal.js
  profile:
    - public/fancybox/jquery.mousewheel-3.0.4.pack.js
    - public/fancybox/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/plugins/jquery.elastic.source.js
    - public/javascripts/plugins/jquery.timeago.js
    - public/javascripts/plugins/date.js
    - public/javascripts/plugins/jquery-autocomplete/lib/jquery.bgiframe.min.js
    - public/javascripts/plugins/jquery-autocomplete/lib/jquery.ajaxQueue.js
    - public/javascripts/plugins/jquery-autocomplete/lib/thickbox-compressed.js
    - public/javascripts/plugins/jquery-autocomplete/jquery.autocomplete.js
    - public/javascripts/plupload/plupload.js
    - public/javascripts/plupload/plupload.full.js
    - public/javascripts/plupload/jquery.ui.plupload/jquery.ui.plupload.js
    - public/javascripts/plugins/actwitty-custom.js
    - public/javascripts/plugins/jquery.alphanumeric.pack.js
    - public/javascripts/plugins/expander_readmore.js
    - public/javascripts/plugins/jquery-list-splitter/jquery.easyListSplitter.js
    - public/javascripts/actwitty/alpha/custom.js
    - public/javascripts/actwitty/default_channels.js
    - public/javascripts/actwitty/home_page_inputs.js
    - public/javascripts/actwitty/alpha/actwitty_profile_helpers.js
    - public/javascripts/actwitty/aw_slider.js
    - public/javascripts/actwitty/boxer.js
    - public/javascripts/actwitty/settings_page.js
    - public/javascripts/actwitty/profile_lib.js
    - public/javascripts/actwitty/profile_mode_manager.js
    - public/javascripts/actwitty/profile_attachments.js
    - public/javascripts/actwitty/profile_filter.js
    - public/javascripts/actwitty/profile_modals.js
    - public/javascripts/actwitty/profile_entities.js
    - public/javascripts/actwitty/profile_related_followings.js
    - public/javascripts/actwitty/profile_locations.js
    - public/javascripts/actwitty/profile_channels.js
    - public/javascripts/actwitty/profile_stream_share.js
    - public/javascripts/actwitty/profile_subscribers.js
    - public/javascripts/actwitty/profile_facebook.js
    - public/javascripts/actwitty/profile_subscriptions.js
    - public/javascripts/actwitty/profile_follow.js
    - public/javascripts/actwitty/profile_summary.js
    - public/javascripts/actwitty/profile_streams_sidelists.js
    - public/javascripts/actwitty/drafts.js
    - public/javascripts/actwitty/profile_stream.js
    - public/javascripts/actwitty/profile.js
    - public/javascripts/actwitty/single_post.js
    - public/javascripts/actwitty/edit_box_page.js
    - public/javascripts/actwitty/entity_page.js
    - public/javascripts/actwitty/channel_page.js
    - public/javascripts/actwitty/location_page.js
    - public/javascripts/actwitty/profile_main.js
    - public/javascripts/actwitty/profile_people.js
    - public/javascripts/actwitty/profile_images.js
    - public/javascripts/actwitty/profile_videos.js
    - public/javascripts/actwitty/tooltip.js   
    - public/javascripts/actwitty/profile_fb.js
    - public/javascripts/actwitty/profile_followers.js
    - public/javascripts/actwitty/profile_followings.js


  main:
    - public/javascripts/rails.js
    - public/javascripts/vendor/jqueryui.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/jquery.hotkeys.js
    - public/javascripts/vendor/jquery.autoresize.min.js
    - public/javascripts/vendor/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
  mobile:
    - public/javascripts/vendor/jquery152.min.js
    - public/javascripts/vendor/jquery.mobile-1.0a4.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/rails.js
  mailchimp:
    - public/javascripts/vendor/mailchimp/jquery.form.js
    - public/javascripts/vendor/mailchimp/jquery.validate.js
    - public/javascripts/vendor/mailchimp/jquery126.min.js

stylesheets:
  defaults:
    - public/stylesheets/actwitty/alpha/actwitty_buttons.css
    - public/stylesheets/actwitty/alpha/home_layout.css
    - public/stylesheets/actwitty/alpha/images_layout.css
    - public/stylesheets/actwitty/alpha/multimedia.css
    - public/stylesheets/actwitty/alpha/actwitty-profile-settings.css
    - public/stylesheets/actwitty/alpha/actwitty-channel-page.css
    - public/stylesheets/actwitty/alpha/comments-streams.css
    - public/stylesheets/actwitty/alpha/campaign-streams.css
    - public/stylesheets/actwitty/alpha/share-streams.css
    - public/stylesheets/actwitty/alpha/modals.css
    - public/stylesheets/actwitty/alpha/boxer.css
    - public/stylesheets/actwitty/alpha/jquery.fancybox-1.3.4.css
    - public/stylesheets/plupload/jquery.ui.plupload.css
    - public/stylesheets/plupload/jquery.plupload.queue.css
    - public/stylesheets/actwitty/signin.css
    - public/stylesheets/actwitty/about.css
    - public/stylesheets/actwitty/profile.css
    - public/stylesheets/actwitty/validations.css
    - public/stylesheets/actwitty/simple_form.css
    - public/stylesheets/actwitty/image_scroll.css
    - public/stylesheets/actwitty/alpha/main_page_user.css
    - public/stylesheets/actwitty/alpha/actwitty_home_page.css
    - public/stylesheets/plugins/jquery-autocomplete/jquery.autocomplete.css
    - public/stylesheets/plugins/jquery-autocomplete/lib/thickbox.css
    - public/stylesheets/actwitty/alpha/settings.css
    - public/stylesheets/actwitty/alpha/fb_friends.css

