package_assets: on 
embed_assets: datauri
compress_assets: off
gzip_assets: off
javascripts:
  flash_socket:
    - public/javascripts/vendor/FABridge.js
    - public/javascripts/vendor/swfobject.js
    - public/javascripts/vendor/web_socket.js
  jquery:
    - public/javascripts/jquery/jquery-1.6.2.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
  actwittyall:
    - public/javascripts/jquery/jquery-ui-1.8.14/ui/minified/jquery-ui.min.js
    - public/javascripts/actwitty/refactor/common/externals/rails/jquery_ujs.js
    - public/javascripts/actwitty/refactor/common/externals/rails/rails.validations.js
    - public/javascripts/actwitty/refactor/common/externals/rails/rails.validations.custom.js
    - public/javascripts/actwitty/refactor/lpm/aw_lpm_user_updates.js
    - public/javascripts/actwitty/refactor/lpm/aw_lpm_signin.js
    - public/javascripts/actwitty/refactor/server_requests/aw_post_requests.js
    - public/javascripts/actwitty/refactor/server_requests/aw_get_requests.js
    - public/javascripts/actwitty/refactor/common/aw_jquery_manager.js
    - public/javascripts/actwitty/refactor/common/aw_cmn_default_channel_themes.js
    - public/javascripts/actwitty/refactor/common/aw_jquery_libs.js
  profile_commons:
    - public/javascripts/actwitty/refactor/ppm/common/aw_cmn_more_cookie_manager.js
    - public/javascripts/actwitty/refactor/ppm/header/aw_ppm_header_main.js
    - public/javascripts/actwitty/refactor/ppm/inputs/aw_ppm_input_location.js
    - public/javascripts/actwitty/refactor/ppm/inputs/aw_ppm_input_main.js
    - public/javascripts/actwitty/refactor/ppm/inputs/aw_ppm_input_channel_names.js
    - public/javascripts/actwitty/refactor/ppm/externals/plupload/plupload.js
    - public/javascripts/actwitty/refactor/ppm/externals/plupload/plupload.full.js
    - public/javascripts/actwitty/refactor/ppm/externals/plupload/jquery.ui.plupload/jquery.ui.plupload.js
  profile_channels:
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_channel_renderer.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_channel_events.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_dyn_analytc.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_user_channels.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_subscribed_channels.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_all_channels.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_all_mentions.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_all_locations.js
   
  profile_streams:
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_renderer.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_events.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_timeline.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_video_timeline.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_image_timeline.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_attachments.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_likes.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_comments.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_mentions.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_external_shares.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_mention_updates.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_filters.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_all_people.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_all_mentions.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_all_locations.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_modal_manager.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_enricher.js
  profile_main_extra:
    - public/javascripts/actwitty/refactor/common/externals/fancybox/jquery.mousewheel-3.0.4.pack.js
    - public/javascripts/actwitty/refactor/common/externals/fancybox/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/actwitty/refactor/common/externals/input/jquery.elastic.source.js
    - public/javascripts/actwitty/refactor/common/externals/input/jquery.alphanumeric.pack.js
    - public/javascripts/actwitty/refactor/common/externals/date/jquery.timeago.js
    - public/javascripts/plugins/date.js
    - public/javascripts/plugins/actwitty-custom.js
    - public/javascripts/plugins/expander_readmore.js
    - public/javascripts/plugins/jquery-list-splitter/jquery.easyListSplitter.js
    - public/javascripts/actwitty/alpha/custom.js
  autocomplete:
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/lib/jquery.bgiframe.min.js
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/lib/jquery.ajaxQueue.js
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/lib/thickbox-compressed.js
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/jquery.autocomplete.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/vendor/jqueryui.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/jquery.hotkeys.js
    - public/javascripts/vendor/jquery.autoresize.min.js
    - public/javascripts/vendor/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
  mobile:
    - public/javascripts/vendor/jquery152.min.js
    - public/javascripts/vendor/jquery.mobile-1.0a4.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/rails.js
  mailchimp:
    - public/javascripts/vendor/mailchimp/jquery.form.js
    - public/javascripts/vendor/mailchimp/jquery.validate.js
    - public/javascripts/vendor/mailchimp/jquery126.min.js

stylesheets:
  defaults:
    - public/stylesheets/actwitty/refactor/aw_common/aw_button_styles.css
  landing_pages:
    - public/stylesheets/actwitty/refactor/aw_lpm/aw_landing_page_main.css
    - public/stylesheets/actwitty/refactor/aw_lpm/aw_lpm_dyn_chn_updates.css
    - public/stylesheets/actwitty/refactor/aw_lpm/signins/aw_signup_page_main.css
    - public/stylesheets/actwitty/refactor/aw_lpm/signins/aw_signin_page_main.css
    - public/stylesheets/actwitty/refactor/aw_lpm/signins/aw_signin_forgot_password.css
    - public/stylesheets/actwitty/refactor/aw_lpm/external/simpleform/simple_form.css
  profile_page_commons:  
    - public/stylesheets/actwitty/refactor/aw_ppm/common/aw_profile_header.css
    - public/stylesheets/actwitty/refactor/aw_ppm/common/aw_profile_input.css
  profile_page_channels:
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_profile_page_main_channel.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_dyn_chn_page.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_dyn_chn_page_mentions.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_dyn_chn_page_locations.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_chn_dyn_analytc.css
  profile_page_streams:
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_profile_page_main_stream.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_main_streams.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_attachments.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_actions.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_modal.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_likes.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_shares.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_comments.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/videos/aw_ppm_dyn_stm_main_videos.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/images/aw_ppm_dyn_stm_main_images.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_right_side_mentions.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_right_side_locations.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_right_side_people.css
  profile_page_externals:
    - public/stylesheets/actwitty/refactor/aw_ppm/external/plupload/jquery.ui.plupload.css
    - public/stylesheets/actwitty/refactor/aw_ppm/external/plupload/jquery.plupload.queue.css
    - public/stylesheets/actwitty/refactor/aw_ppm/external/jquery-autocomplete/jquery.autocomplete.css
    - public/stylesheets/actwitty/refactor/aw_ppm/external/jquery-autocomplete/lib/thickbox.css
    - public/javascripts/actwitty/refactor/common/externals/fancybox/jquery.fancybox-1.3.4.css
  extras:
    - public/stylesheets/actwitty/alpha/images_layout.css
    - public/stylesheets/actwitty/alpha/multimedia.css
    - public/stylesheets/actwitty/alpha/actwitty-profile-settings.css
    - public/stylesheets/actwitty/alpha/actwitty-channel-page.css
    - public/stylesheets/actwitty/alpha/comments-streams.css
    - public/stylesheets/actwitty/alpha/campaign-streams.css
    - public/stylesheets/actwitty/alpha/share-streams.css
    - public/stylesheets/actwitty/alpha/boxer.css
    - public/stylesheets/actwitty/about.css
    - public/stylesheets/actwitty/validations.css
    - public/stylesheets/actwitty/simple_form.css
    - public/stylesheets/actwitty/image_scroll.css
    - public/stylesheets/actwitty/alpha/main_page_user.css
    - public/stylesheets/actwitty/alpha/actwitty_home_page.css
    - public/stylesheets/actwitty/alpha/settings.css
    - public/stylesheets/actwitty/alpha/fb_friends.css

