package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  flash_socket:
    - public/javascripts/vendor/FABridge.js
    - public/javascripts/vendor/swfobject.js
    - public/javascripts/vendor/web_socket.js
  jquery:
    - public/javascripts/vendor/jquery152.min.js
    - public/javascripts/rails.js
    - public/javascripts/vendor/jqueryui.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/vendor/jqueryui.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/jquery.hotkeys.js
    - public/javascripts/vendor/jquery.autoresize.min.js
    - public/javascripts/vendor/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/vendor/facebox.js
    - public/javascripts/vendor/timeago.js
    - public/javascripts/vendor/Mustache.js
    - public/javascripts/vendor/charCount.js
  mobile:
    - public/javascripts/vendor/jquery152.min.js
    - public/javascripts/vendor/jquery.mobile-1.0a4.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/rails.js
  mailchimp:
    - public/javascripts/vendor/mailchimp/jquery.form.js
    - public/javascripts/vendor/mailchimp/jquery.validate.js
    - public/javascripts/vendor/mailchimp/jquery126.min.js
  people:
    - public/javascripts/vendor/jquery.autoSuggest.custom.js
  profile:
    - public/javascripts/vendor/jquery.autoSuggest.custom.js

stylesheets:
  default:
    - public/stylesheets/vendor/facebox.css
    - public/stylesheets/vendor/fileuploader.css
    - public/stylesheets/vendor/tipsy.css
    - public/stylesheets/vendor/autoSuggest.css
