package_assets: on 
embed_assets: datauri
compress_assets: off
gzip_assets: off
javascripts:
  flash_socket:
    - public/javascripts/vendor/FABridge.js
    - public/javascripts/vendor/swfobject.js
    - public/javascripts/vendor/web_socket.js
  jquery:
    - public/javascripts/jquery/jquery-1.6.2.min.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
  actwittyall:
    - public/javascripts/jquery/jquery-ui-1.8.14/ui/minified/jquery-ui.min.js
    - public/javascripts/actwitty/refactor/common/externals/rails/jquery_ujs.js
    - public/javascripts/actwitty/refactor/common/externals/rails/rails.validations.js
    - public/javascripts/actwitty/refactor/common/externals/rails/rails.validations.custom.js
    - public/javascripts/actwitty/refactor/lpm/aw_lpm_user_updates.js
    - public/javascripts/actwitty/refactor/lpm/aw_lpm_signin.js
    - public/javascripts/actwitty/refactor/server_requests/aw_post_requests.js
    - public/javascripts/actwitty/refactor/server_requests/aw_get_requests.js
    - public/javascripts/actwitty/refactor/common/aw_jquery_manager.js
    - public/javascripts/actwitty/refactor/common/aw_cmn_channel_theme_reg.js
    - public/javascripts/actwitty/refactor/common/aw_cmn_default_channel_themes.js
    - public/javascripts/actwitty/refactor/common/aw_jquery_libs.js
  profile_commons:
    - public/javascripts/actwitty/refactor/ppm/common/aw_cmn_more_cookie_manager.js
    - public/javascripts/actwitty/refactor/ppm/header/aw_ppm_header_main.js
    - public/javascripts/actwitty/refactor/ppm/inputs/aw_ppm_input_location.js
    - public/javascripts/actwitty/refactor/ppm/inputs/aw_ppm_input_main.js
    - public/javascripts/actwitty/refactor/ppm/inputs/aw_ppm_input_channel_names.js
    - public/javascripts/actwitty/refactor/ppm/externals/plupload/plupload.js
    - public/javascripts/actwitty/refactor/ppm/externals/plupload/plupload.full.js
    - public/javascripts/actwitty/refactor/ppm/externals/plupload/jquery.ui.plupload/jquery.ui.plupload.js
    - public/javascripts/actwitty/refactor/common/externals/fancybox/jquery.mousewheel-3.0.4.pack.js
    - public/javascripts/actwitty/refactor/common/externals/fancybox/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/actwitty/refactor/common/externals/input/jquery.alphanumeric.pack.js
    - public/javascripts/actwitty/refactor/common/externals/date/jquery.timeago.js
    
  profile_settings:
    - public/javascripts/actwitty/refactor/spm/user_profile/aw_spm_setting.js
    - public/javascripts/actwitty/refactor/spm/user_profile/aw_spm_setting_location.js
  profile_channel_settings:
    - public/javascripts/actwitty/refactor/spm/channel_profile/aw_cspm_setting.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_dyn_analytc.js
  profile_channels:
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_channel_renderer.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_channel_events.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_dyn_analytc.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_user_channels.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_subscribed_channels.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_all_channels.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_all_mentions.js
    - public/javascripts/actwitty/refactor/ppm/channels/aw_ppm_chn_all_locations.js
    - public/javascripts/actwitty/refactor/ppm/streams/facebook/aw_ppm_stream_facebook_srv_request.js
    - public/javascripts/actwitty/refactor/ppm/streams/facebook/aw_ppm_stream_facebook_renders.js
  profile_streams:
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_renderer.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_events.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_timeline.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_video_timeline.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_image_timeline.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_attachments.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_likes.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_comments.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_mentions.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_external_shares.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_mention_updates.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_filters.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_all_people.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_all_mentions.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_all_locations.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_modal_manager.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_enricher.js
    - public/javascripts/actwitty/refactor/ppm/streams/facebook/aw_ppm_stream_facebook_srv_request.js
    - public/javascripts/actwitty/refactor/ppm/streams/facebook/aw_ppm_stream_facebook_renders.js
    - public/javascripts/actwitty/refactor/ppm/streams/aw_ppm_stream_rename_channel.js
  profile_main_extra:
    - public/javascripts/actwitty/refactor/common/externals/input/jquery.elastic.source.js
    - public/javascripts/plugins/date.js
    - public/javascripts/plugins/actwitty-custom.js
    - public/javascripts/plugins/expander_readmore.js
    - public/javascripts/plugins/jquery-list-splitter/jquery.easyListSplitter.js
  profile_single_post_page:
    - public/javascripts/actwitty/refactor/ppm/streams/substates/singlepost/aw_ppm_stream_singlepost.js
  channel_page:
    - public/javascripts/actwitty/refactor/ppm/streams/substates/channel_page/aw_ppm_stream_channel_page.js
  mention_page:
    - public/javascripts/actwitty/refactor/ppm/streams/substates/mention_page/aw_ppm_stream_mention_page.js
  location_page:
    - public/javascripts/actwitty/refactor/ppm/streams/substates/location_page/aw_ppm_stream_location_page.js
  autocomplete:
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/lib/jquery.bgiframe.min.js
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/lib/jquery.ajaxQueue.js
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/lib/thickbox-compressed.js
    - public/javascripts/actwitty/refactor/common/externals/jquery-autocomplete/jquery.autocomplete.js
  highcharts:
    - public/javascripts/actwitty/refactor/ppm/externals/highcharts/highcharts.js
    - public/javascripts/actwitty/refactor/ppm/externals/highcharts/modules/exporting.js
    - public/javascripts/actwitty/refactor/ppm/externals/highcharts/themes/gray.js
  charts_analytics:
    - public/javascripts/actwitty/refactor/ppm/streams/analytics/aw_ppm_chart_main.js
    - public/javascripts/actwitty/refactor/ppm/streams/analytics/aw_ppm_chart_all_channels_source_distribution.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/vendor/jqueryui.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/jquery.hotkeys.js
    - public/javascripts/vendor/jquery.autoresize.min.js
    - public/javascripts/vendor/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
  mobile:
    - public/javascripts/vendor/jquery152.min.js
    - public/javascripts/vendor/jquery.mobile-1.0a4.js
    - public/javascripts/vendor/jquery.infinitescroll.min.js
    - public/javascripts/rails.js
  mailchimp:
    - public/javascripts/vendor/mailchimp/jquery.form.js
    - public/javascripts/vendor/mailchimp/jquery.validate.js
    - public/javascripts/vendor/mailchimp/jquery126.min.js




stylesheets:
  defaults:
    - public/stylesheets/actwitty/refactor/aw_common/aw_button_styles.css
    - public/stylesheets/actwitty/refactor/aw_common/aw_modal_boxes.css
    - public/stylesheets/actwitty/refactor/aw_common/aw_loading_animation.css
  landing_pages:
    - public/stylesheets/actwitty/refactor/aw_lpm/aw_landing_page_main.css
    - public/stylesheets/actwitty/refactor/aw_lpm/aw_lpm_dyn_chn_updates.css
    - public/stylesheets/actwitty/refactor/aw_lpm/signins/aw_signup_page_main.css
    - public/stylesheets/actwitty/refactor/aw_lpm/signins/aw_signin_page_main.css
    - public/stylesheets/actwitty/refactor/aw_lpm/signins/aw_signin_forgot_password.css
    - public/stylesheets/actwitty/refactor/aw_lpm/external/simpleform/simple_form.css
  profile_page_commons:  
    - public/stylesheets/actwitty/refactor/aw_ppm/common/aw_profile_header.css
    - public/stylesheets/actwitty/refactor/aw_ppm/common/aw_profile_input.css
  profile_page_settings:
    - public/stylesheets/actwitty/refactor/aw_ppm/settings/aw_ppm_user_profile_settings.css
  profile_channel_settings:
    - public/stylesheets/actwitty/refactor/aw_ppm/settings/aw_ppm_user_channel_settings.css
#   aw_ppm_chn_dyn_analytc.css will be needed in channel settings page if we need to show analytics here
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_chn_dyn_analytc.css
  profile_page_channels:
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_profile_page_main_channel.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_dyn_chn_page.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_dyn_chn_page_mentions.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_dyn_chn_page_locations.css
    - public/stylesheets/actwitty/refactor/aw_ppm/channel/aw_ppm_chn_dyn_analytc.css
  profile_page_streams:
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_profile_page_main_stream.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_main_streams.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_attachments.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_actions.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_likes.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_shares.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_comments.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/videos/aw_ppm_dyn_stm_main_videos.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/images/aw_ppm_dyn_stm_main_images.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_right_side_mentions.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_right_side_locations.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_right_side_people.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/facebook/aw_ppm_dyn_stm_facebook.css
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/aw_ppm_dyn_stm_rename_chn.css
  profile_page_externals:
    - public/stylesheets/actwitty/refactor/aw_ppm/external/plupload/jquery.ui.plupload.css
    - public/stylesheets/actwitty/refactor/aw_ppm/external/plupload/jquery.plupload.queue.css
    - public/stylesheets/actwitty/refactor/aw_ppm/external/jquery-autocomplete/jquery.autocomplete.css
    - public/stylesheets/actwitty/refactor/aw_ppm/external/jquery-autocomplete/lib/thickbox.css
    - public/javascripts/actwitty/refactor/common/externals/fancybox/jquery.fancybox-1.3.4.css
  profile_single_post_page:
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/singlepost/aw_ppm_singlepost_main.css
  channel_page:
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/channel_page/aw_ppm_channel_page_main.css
  mention_page:
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/mention_page/aw_ppm_mention_page_main.css
  location_page:
    - public/stylesheets/actwitty/refactor/aw_ppm/streams/location_page/aw_ppm_location_page_main.css

