sports:
  type: /sports
  channel: sports
  hierarchy: /
  name: sports
  personalize: sporty
  sentence: things on sports
  end_sentence: and things on sports
  fb_timeline: sports
automobiles:
  type: /automobiles
  channel: automobiles
  hierarchy: /
  name: automobiles
  personalize: roadie
  sentence: roads, automobiles, cars
  end_sentence: roads, automobiles and cars
  fb_timeline: automobiles
entertainment:
  type: /entertainment
  channel: entertainment
  hierarchy: /
  name: entertainment
  personalize: entertainer
  sentence: music, movies, entertainment
  end_sentence: music, movies and entertainment
  fb_timeline: shares about entertainment
games:
  type: /games
  channel: games
  hierarchy: /
  name: toys and games
  personalize: gamer
  sentence: fun, games
  end_sentence: fun and games
  fb_timeline: shares about fun and games
leisure:
  type: /leisure
  channel: leisure
  hierarchy: /
  name: leisure,recreation and fashion
  personalize: fashionista 
  sentence: leisure, recreation, fashion
  end_sentence: leisure, recreation and fashion
  fb_timeline: shares about leisure recreation and fashions
nonprofit:
  type: /nonprofit
  channel: nonprofit
  hierarchy: /
  name: nonprofits
  personalize: philanthropist
  sentence: philanthropy, not-for-profits
  end_sentence: philanthropy and not-for-profits
  fb_timeline: shares about nonprofits
stories:
  type: /stories
  channel: stories
  hierarchy: /
  name: stories
  sentence: general things with friends
  end_sentence: and general things with friends
  fb_timeline: shares in general things
technology:
  type: /technology
  channel: technology
  hierarchy: /
  name: technology
  sentence: science, gadgets, technology
  end_sentence: science, gadgets and technology
  fb_timeline: technology
world:
  type: /world
  channel: world
  hierarchy: /
  name: society, religion, environment, law, crime and politics
  personalize: social
  sentence: topics on society, religion, environment, law, crime and politics
  end_sentence: topics on society, religion, environment, law, crime and politics
  fb_timeline: shares in world

animals:
  type: /animals
  channel: animals
  hierarchy: /
  name: pets and animals
  sentence: things about animals, plants and wildlife
  end_sentence: things about animals, plants and wildlife
  fb_timeline: shares about animals
business:
  type: /business
  channel: business
  hierarchy: /
  name: business
  sentence: market, business, entreprenuership 
  end_sentence: market, business and entreprenuership
  fb_timeline: shares about business
health:
  type: /health
  channel: health
  hierarchy: /
  name: health, medical and phrama
  sentence: fitness, health, medicines, pharmaceuticals
  end_sentence: fitness, health, medicines and pharmaceuticals
  fb_timeline: shares about health
food:
  type: /food
  channel: food
  hierarchy: /
  name: food and drink
  sentence: recipes, restaurants, food, drink
  end_sentence: recipes, restaurants, food and drink
  fb_timeline: shares about food
books:
  type: /books
  channel: books
  hierarchy: /
  name: books and articles
  personalize: reader
  sentence: articles, books, reading material
  end_sentence: articles, books and reading material
  fb_timeline: shares about reads
arts:
  type: /arts
  channel: arts
  hierarchy: /
  name: arts and design
  personalize: artist
  sentence: aesthetics, art, design
  sentence: aesthetics, art and design
  fb_timeline: shares about arts
places:
  type: /places
  channel: places
  hierarchy: /
  name: places, travel and events 
  personalize: tourist
  sentence: tourism, places, travel, events, adventures
  end_sentence: tourism, places, travel, events, adventures
  fb_timeline: shares about places
home:
  type: /home
  channel: home
  hierarchy: /
  name: home
  personalize: family person
  sentence: family, managing home, furnishings, home decor
  end_sentence: family, managing home, furnishings and home decor
  fb_timeline: shares about home
education:
  type: /eductaion
  channel: education
  hierarchy: /
  name: education
  personalize: teacher
  sentence: literacy, education, schools, colleges
  end_sentence: literacy, education, schools and colleges
  fb_timeline: shares about education
hobbies:
  type: /hobbies
  channel: hobbies
  hierarchy: /
  name: hobbies and interests
  personalize: hobbyist
  sentence: hobbies, personal interests, amateurism
  end_sentence: hobbies, personal interests and amateurism
  fb_timeline: shares about hobbies
products:
  type: /products
  channel: products
  hierarchy: /
  name: brands and products
  personalize: shopaholic
  sentence: brands, products, shopping or marketting
  end_sentence: brands, products and shopping or marketting
  fb_timeline: shares about products
environment:
  type: /environment
  channel: environment
  hierarchy: /
  name: environment
  personalize: environmentalist
  sentence: nature, weather
  end_sentence: and things on environment
  fb_timeline: environment
