sports:
  type: /sports
  channel: sports
  hierarchy: /
  name: sports
cars:
  type: /cars
  channel: cars
  hierarchy: /
  name: cars
entertainment:
  type: /entertainment
  channel: entertainment
  hierarchy: /
  name: entertainment
games:
  type: /games
  channel: games
  hierarchy: /
  name: toys and games
fashion:
  type: /fashion
  channel: fashion
  hierarchy: /
  name: fashion and style
nonprofits:
  type: /nonprofit
  channel: nonprofit
  hierarchy: /
  name: nonprofits
stories:
  type: /stories
  channel: stories
  hierarchy: /
  name: stories
technology:
  type: /technology
  channel: technology
  hierarchy: /
  name: technology
politics:
  type: /politics
  channel: politics
  hierarchy: /
  name: society and politics
animals:
  type: /animals
  channel: animals
  hierarchy: /
  name: pets and animals
business:
  type: /business
  channel: business
  hierarchy: /
  name: business
health:
  type: /health
  channel: health
  hierarchy: /
  name: health
food:
  type: /food
  channel: food
  hierarchy: /
  name: food and drink
books:
  type: /books
  channel: books
  hierarchy: /
  name: books and articles
arts:
  type: /arts
  channel: arts
  hierarchy: /
  name: arts and design
places:
  type: /travel
  channel: travel
  hierarchy: /
  name: travel and places
events:
  type: /events
  channel: events
  hierarchy: /
  name: holidays and events
home:
  type: /home
  channel: home
  hierarchy: /
  name: home
education:
  type: /eductaion
  channel: education
  hierarchy: /
  name: education
hobbies:
  type: /hobbies
  channel: hobbies
  hierarchy: /
  name: hobbies and interests