development: &default
  aws_bucket_name: TestCloudActwitty
  aws_access_key_id: AKIAJMH2GTITVBHDSZ6Q
  aws_secret_access_key: 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

  pusher_app_id: 8166
  pusher_service_key: 1c9a6ce5543a3dc6cd5b
  pusher_service_secret: e3442602c6f83308f025
production:
  <<: *default
test:
  <<: *default