development: &default
  aws_bucket_name: TestCloudActwitty
  aws_access_key_id: AKIAJMH2GTITVBHDSZ6Q
  aws_secret_access_key: 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

  pusher_app_id: 8165
  pusher_key_id: e56f227bc500d2fb8364
  pusher_secret_key: e0948ca7a8b1c398dba3

production:
  <<: *default

  pusher_app_id: 8164
  pusher_key_id: 082b78af7b43fe2cecea
  pusher_secret_key: 02e84edceda36cc1bce6
test:
  <<: *default