# Enter your per-environment constants below

development: &default
  activity_text_length:                 8192
  comment_text_length:                  2048
  url_length:                           1024
  activity_name_length:                 255
  caption_text_length:                  64
  sub_title_length:                     255
  source_name_length:                   64
  action_name_length:                   64    #actions like from "share", "post" "comment" "like" etc
  document_name_length:                 255
  document_mime_length:                 64
  campaign_name_length:                 64
  document_provider_length:             64
  document_category_length:             32
  tag_length:                           64
  location_name_length:                 1024
  max_number_of_documents_pulled:       50

  #in megabytes
  max_document_size:                    0.5

  #after this length "..." will be shown
  max_string_len_for_display:           10

  #in one pull of an activity or summary in order of latest updates
  max_number_of_activities:             50

  max_number_of_a_type_in_summmary:     6

  max_number_of_summmary:               50
  max_number_of_users:                  50
  max_number_of_entities:               50
  max_number_of_locations:               50


  default_comment_string:               "Comment"

  url_validator:                        "/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix"

  entity_controller:                    "entities"
  user_controller:                      "users"
  location_controller:                  "locations"
  activity_word_controller:             "activity_words"
  activity_controller:                  "activities"
  comment_controller:                   "comments"
  document_controller:                  "documents"

  #CSS class names for styling individual links
  activity_entity_class:                "js_activity_entity"
  activity_mention_class:               "js_activity_mention"
  activity_location_class:              "js_activity_location"
  activity_word_class:                  "js_activity_word"

  campaign_username_class:              "js_campaign_username"
  campaign_activity_class:              "js_campaign_activity"
  campaign_entity_class:                "js_campaign_entity"
  campaign_location_class:              "js_campaign_location"
  campaign_comment_class:               "js_campaign_comment"
  campaign_authorname_class:            "js_campaign_author_name"
  campaign_document_class:              "js_campaign_document"

  comment_authorname_class:             "js_comment_author_name"
  comment_activity_class:               "js_comment_activity"
  comment_document_class:               "js_comment_document"
  comment_username_class:               "js_comment_username"

  comment_class:
  invalid_resource_id:                  0

  entitiy_no_image:                     "/images/entity/default.png"
  user_no_image:                        "/images/profile/default.png"
  entity_image_thumb_base:               "http://api.freebase.com/api/trans/image_thumb/guid/"
  entity_image_raw_base:                 "http://api.freebase.com/api/trans/raw/guid/"
  entity_description_url:               "http://en.wikipedia.org/wiki/index.html?curid="

  summary_word_count:                   15
  summary_document_count:               5
  summary_entity_count:                 5
  summary_location_count:               5
  summary_friend_count:                 5
  summary_text_count:                   5


  stream_max_count:                     15
  #LOCATION_TYPE
  location_type_web:                    1
  location_type_geo:                    2
  location_type_unresolved:             3

  #STATUS
  status_saved:                     1
  status_public:                    2
  status_private:                   3
  status_shared:                    4  #need the loop visibility later

  #these are defined SOURCE_NAME
  #there can be custom sources like emails and mobile number
  source_actwitty:                "actwitty"
  source_actwitty_meta:           "actwitty_meta"
  source_twitter:                 "twitter"
  source_facebook:                "facebook"
  source_dropbox:                 "dropbox"
  source_gplus:                   "gplus"
  source_tumblr:                  "tumblr"
  source_posterous:               "posterous"

  #SOURCES CURRENTLY ACTIVE - MEANS WE ARE PULLING DATA FROM THEM
  sources_active_list:            [actwitty, actwitty_meta]

  #CAMPAIGN_TYPES
  campaign_none:                       1  #used for internal activities generated because of commenting or campaign creation
  campaign_like:                       2
  campaign_support:                    3
  campaign_join:                       4

  #document providers
  provider_actwitty:                  "actwitty.com"
  provider_dropbox:                   "dropbox.com"
  provider_youtube:                   "youtube.com"
  provider_vimeo:                     "vimeo.com"
  provider_flickr:                    "flickr.com"
  provider_twitpic:                   "twitpic.com"
  provider_lastfm:                     "last.fm"
  provider_spotify:                    "spotify.com"

  #Remote Document mime - They are custom not standard
  #TODO need to check properly
  #Refer http://en.wikipedia.org/wiki/Internet_media_type
  mime_remote_image:                 "image/remote"
  mime_remote_video:                 "video/remote"
  mime_remote_document:              "application/remote"
  mime_remote_music:                 "audio/remote"
  mime_remote_link:                  "link/remote"

  #TAG TYPE
  tag_type_hash:                     1    #mentioned
  tag_type_blog:                     2    #explicitly mentioned by user as blog tags
  tag_type_semantic:                 3    #tags from sources like zemanta

#  #Document category
#  category_image:                     "image"
#  category_audio:                     "audio"
#  category_video:                     "video"
#  category_document:                  "application"

  #Video Sources
  video_sources:                      youtube\.com|vimeo\.com
  video_extensions:                    \.mpg|\.mpeg|\.flv|\.mp4        # \ is used to escape dots in regular expression

  #Image Sources
  image_sources:                      flickr\.com|twitpic\.com
  image_extensions:                    \.jpeg|\.jpg|\.bmp

  #document sources
  document_sources:                   dropbox\.com
  document_extensions:                \.xlsx|\.xls|\.docx|\.doc|\.pptx|\.ppt|\.pdf

  #audio Sources
  audio_sources:                      last\.fm|spotify\.com
  audio_extensions:                   \.mp3|\.rm|\.aac


  #Tag List
  sanity_tags:                        %w(b i u mention img name id a)

  #attributes List
  sanity_attributes:                    %w(href value class)

  #cloud actions
  cloud_action_document_destroy:      1

  #number of documents to deleted from garbage_document table at once
  max_document_destroy_from_cloud:    2

  #Theme Color
  theme_default_fg_color:             "0xffffff00"
  theme_default_bg_color:             "0xffffff00"

  #Theme type
  theme_default:                      1
  theme_color:                        2
  theme_document:                     3

  #Theme Style
  theme_style_centerd:                 1
  theme_style_tiled:                   2
  theme_style_stretched:               3

  #PAGE STATES
  page_state_user:                    1
  page_state_subscribed:              2
  page_state_all:                     3
  page_state_public:                  4

  #Cloud Keys
  cloud_keys:                         "config/cloud_keys.yml"
  
  #FB/Twitter ids registered using cloud@actwitty.com
  #FB url: https://developers.facebook.com/apps
  #Twitter url: https://dev.twitter.com/apps
  facebook_app_id:                    '172893766124779'
  facebook_secret_key:                'd842d4c68c7698a9e0a0823333d691a2'
  twitter_consumer_key:               'WWeEDiFxubwhlr45cEXDqw'
  twitter_consumer_secret:            'J3EIt2m2drozoyHEOHu3MR8nO78RwNPjD7kYTRzJ8'


  #User Types
   #User Types
  user_type_regular:                  0
  user_type_admin:                    1
  user_type_web_admin:                2                    

  #FOR PUBLIC SHOW
  ghost_user_email:                   "administrator@actwitty.com"

  #Allowed to see internals
  #Devloper:change this to reqd email
  authorized_see_internals_email_id:  "aloksrivastava78@gmail.com"

  

  #FOR SUMMARY CATEGORY
  category_min_id:                    1
  category_max_id:                    99999

  sub_category_min_id:                1000000
  sub_category_max_id:                9999999

  category_min_id:                    100000000
  category_max_id:                    999999999

  category_id_length:               255
  category_type_length:               255

  default_category:                   "stories"

  #Rank and Analytics
  number_of_data_points:              90

  age_band_kids:                         "1-12"
  age_band_teens:                        "13-17"
  age_band_geny:                         "18-24"
  age_band_genx:                         "25-34"
  age_band_forties:                      "35-44"
  age_band_fifties:                      "45-54"
  age_band_sixties:                      "55-64"
  age_band_seniors:                      "65+"

  #text categorization
  maximum_import_first_time:              3
  maximum_import_every_time:              3 #imports after first import is done

  data_type_weburl:                     "weburl"
  data_type_youtube:                    youtube    #as it will be used in regex
  data_type_facebook:                   facebook   #as it will be used in regex
  data_type_text:                       "text"

  #Social Fecth
  maximum_time_diff_for_social_fetch:   1 #minutes

  data_sync_not_started:                1
  data_sync_going_on:                   2
  data_sync_done:                       3

production:
  <<: *default
  #constant1:  "overriden value1"
  # Keys and ID for heroku test deployment
  #facebook_app_id:                    '292732787407668'
  #facebook_secret_key:                '82e82066e5e569ef88d052d5eba51b0e'
  #twitter_consumer_key:               'aIJxWpkI3N3Zm3JZPqWVA'
  #twitter_consumer_secret:            'YhreSUMsZoLjdvUM9X4fFbsDlvGPM5uOWmUP9Nxvnbk'

  #######################################################################
  facebook_app_id:                    '180483002026787'
  facebook_secret_key:                '5f9e34ae0030a63796bf8d75b71cbdb7'
  twitter_consumer_key:               'TprGFKB9Puga2MVTqnhg'
  twitter_consumer_secret:            'h0UJ0VRXNPVkVMtuY5p9C8gyk7N9B1uXXMId740ITo'
  #########################################################################

test:
  <<: *default
  #url_validator: "/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix"
