# Enter your per-environment constants below

development: &default
  activity_text_length: 8192
  comment_text_length: 2048
  max_url_length: 1024

  #in megabytes
  max_document_size: 0.5

  url_validator: "/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix"

  entity_controller:  "entities"
  user_controller:  "users"
  location_controller: "locations"
  activity_word_controller:  "activity_words"
  activity_controller: "activities"

  #CSS class names for styling individual links
  activity_entity_class:  "activity_entity"
  activity_mention_class: "activity_mention"
  activity_location_class: "activity_location"
  activity_word_class: "activity_word"

  campaign_username_class: "campaign_username"
  campaign_activity_class: "campaign_activity"
  campaign_entity_class: "campaign_entity"
  campaign_location_class: "campaign_location"

  invalid_resource_id: 0

  entitiy_no_image: "images/entity/default.png"
  user_no_image: "image/profile/default.png"

  summary_word_count: 15
  summary_document_count: 5
  summary_entity_count: 5
  summary_location_count: 5
  summary_friend_count: 5
  summary_text_count: 5
  summary_loop_count: 50

  stream_max_count: 15

production:
  <<: *default
  #constant1:  "overriden value1"

test:
  <<: *default
  #url_validator: "/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix"
