# Enter your per-environment constants below

development: &default
  url_description_length:               255

  max_number_of_summmaries:             50
  max_number_of_users:                  50
  max_number_of_entities:               50
  max_number_of_locations:              50
  max_number_of_activities:             50

  entity_image_url_base:                "https://usercontent.googleapis.com/freebase/v1/image"
  entity_desc_url_base:                 "https://www.googleapis.com/freebase/v1/text"


  #STATUS -> What user sets at actwitty for a message
  status_public:                    1
  status_private:                   2

  #SOURCE_STATUS -> What sources like FB, Twitter etc sets for this m
  status_public_at_source:         1
  status_private_at_source:        2

  #these are defined SOURCE_NAME
  #there can be custom sources like emails and mobile number
  source_actwitty:                "actwitty"
  source_actwitty_meta:           "actwitty_meta"

  #Remote Document mime - They are custom not standard
  #TODO need to check properly
  #Refer http://en.wikipedia.org/wiki/Internet_media_type
  mime_remote_image:                 "image/remote"
  mime_remote_video:                 "video/remote"
  mime_remote_document:              "document/remote"
  mime_remote_music:                 "audio/remote"
  mime_remote_link:                  "link/remote"

  #Video Sources
  video_sources:                      youtube\.com|vimeo\.com|blip\.tv|dailymotion\.com
  video_extensions:                    \.mpg|\.mpeg|\.flv|\.mp4        # \ is used to escape dots in regular expression

  #Image Sources
  image_sources:                      flickr\.com|twitpic\.com
  image_extensions:                    \.jpeg|\.jpg|\.bmp|\.png

  #document sources
  document_sources:                   dropbox\.com
  document_extensions:                \.xlsx|\.xls|\.docx|\.doc|\.pptx|\.ppt|\.pdf

  #audio Sources
  audio_sources:                      last\.fm|spotify\.com
  audio_extensions:                   \.mp3|\.rm|\.aac


  #Tag List
  sanity_tags:                        %w(b i u mention img name id a)

  #attributes List
  sanity_attributes:                    %w(href value class)


  #Cloud Keys
  cloud_keys:                         "config/cloud_keys.yml"

  #Services enabled in actwitty
  services_enabled:                   "config/services.yml"

  #FB/Twitter ids registered using cloud@actwitty.com
  #FB url: https://developers.facebook.com/apps
  #Twitter url: https://dev.twitter.com/apps
  #LinkedIn: https://www.linkedin.com/secure/developer

  facebook_app_id:                    '172893766124779'
  facebook_secret_key:                'd842d4c68c7698a9e0a0823333d691a2'
  twitter_consumer_key:               '2E38F1bp3pmvGMW5hYUPtA'
  twitter_consumer_secret:            'DfqFIM0Y3Z9JWWruWfi5V4kirktL0CpQzhebW9FE'
  linkedin_app_id:                    'g0l32ovkc3vr'
  linkedin_secret_key:                'D7DiN8Al6Ne5nPpE'

  twitpic_reg_key:                    '15c477f5b53647f8af58945dc78b658e'
  freebase_api_key:                   '"AIzaSyBCJSgSk04-G_OTwdm7n9SMJSx_-ceKh8U"'

  #User Types
   #User Types
  user_type_regular:                  0
  user_type_admin:                    1
  user_type_web_admin:                2

  #FOR PUBLIC SHOW
  ghost_user_email:                       "administrator@actwitty.com"

  #Allowed to see internals
  #Devloper:change this to reqd email
  authorized_see_internals_email_ids:  "aloksrivastava78@gmail.com,sudhanshu.saxena@gmail.com"
  authorized_see_internals_secret_key:  "A1B2C3D4E5F6987654321ABCDEFGH"


  #FOR SUMMARY CATEGORY
  default_category:                         "stories"

  #Rank and Analytics
  number_of_data_points:                    53 #max number of weeks in an year
  analytics_default_number_of_week:         5
  analytics_update_summaries:               "summaries"
  analytics_update_user:                    "user"

  #Social Fetch
  max_import_first_time:                  200
  max_import_every_time:                  20
  first_time_feed_storage:                50#100
  every_time_feed_storage:                50#20 #imports after first import is done

  #text categorization
  min_text_length_for_text_categorization:  140
  max_text_length_for_text_categorization:  512
  categorization_concurrency_limit:         15

  #link resolution limit
  link_resolution_batch_limit:              50

  #source object type
  source_object_type_post:                  "post"
  source_object_type_like:                  "like"
  source_object_type_tweet:                 "tweet"
  source_object_type_retweet:               "retweet"

  #Local Actions
  local_action_vote:                        "vote"
  local_action_recommend:                   "recommend"

  #Social Fetch
  maximum_time_diff_for_social_fetch:        64800#in seconds    #18 hours

   #status during social fetch pipeline
  data_sync_new:                            1   #can be deleted in this state
  data_sync_active:                         2
  data_sync_done:                           3   #can be deleted in this state
  data_sync_error:                          4   #can be deleted in this state

  user_service_status_busy:                 "busy"
  user_service_status_idle:                 "idle"


production:
  <<: *default
  #constant1:  "overriden value1"
  # Keys and ID for heroku test deployment
  #facebook_app_id:                    '292732787407668'
  #facebook_secret_key:                '82e82066e5e569ef88d052d5eba51b0e'
  #twitter_consumer_key:               'aIJxWpkI3N3Zm3JZPqWVA'
  #twitter_consumer_secret:            'YhreSUMsZoLjdvUM9X4fFbsDlvGPM5uOWmUP9Nxvnbk'

  #######################################################################
  facebook_app_id:                    '180483002026787'
  facebook_secret_key:                '5f9e34ae0030a63796bf8d75b71cbdb7'
  twitter_consumer_key:               'TprGFKB9Puga2MVTqnhg'
  twitter_consumer_secret:            'h0UJ0VRXNPVkVMtuY5p9C8gyk7N9B1uXXMId740ITo'

  twitpic_reg_key:                    '15c477f5b53647f8af58945dc78b658e'
  freebase_api_key:                   '"AIzaSyBCJSgSk04-G_OTwdm7n9SMJSx_-ceKh8U"'
  #FOR PUBLIC SHOW
  ghost_user_email:                       "administrator@actwitty.com"

  #Allowed to see internals
  #Devloper:change this to reqd email
  authorized_see_internals_email_ids:  "aloksrivastava78@gmail.com,sudhanshu.saxena@gmail.com"
  authorized_see_internals_secret_key:  "A1B2C3D4E5F6987654321ABCDEFGH"
  #########################################################################

test:
  <<: *default

  #test service name
  test_service:                             test
