arts_entertainment: [entertainment, arts]
business: [business]
computer_internet: [technology]
science_technology: [technology]
culture_politics: [politics]
gaming: [games]
health: [health]
law_crime: [politics]
religion: [politics]
recreation: [sports, hobbies]
sports: [sports]
weather:  [places]
song: [entertainment]
movie: [entertainment]
website: [technology]
games: [games]
products: [products]
athlete: [sports]
musician: [entertainment]
music: [entertainment]
tv show: [entertainment]
tv: [entertainment]
book: [books]

