#Alchemy Api
alchemyapi:
  arts_entertainment: [entertainment]
  business: [business]
  computer_internet: [technology]
  science_technology: [technology]
  culture_politics: [world]
  gaming: [games]
  health: [health]
  law_crime: [world]
  religion: [world]
  recreation: [leisure]
  sports: [sports]
  weather: [environment]
  unknown: [stories]

#OpenCalais
opencalais:
  business_finance: [business]
  disaster_accident: [world]
  education: [education]
  entertainment_culture: [entertainment]
  environment: [environment]
  health_medical_pharma: [health]
  hospitality_recreation: [leisure]
  human_interest: [stories]
  human interest: [stories]
  labor: [business]
  law_crime: [world]
  politics: [world]
  social_issues: [world]
  religion_belief: [world]
  war_conflict: [world]
  technology_internet: [technology]
  weather: [environment]
  sports: [sports]
  other: [stories]


#Youtube
youtube:
  autos & vehicles: [automobiles]
  comedy: [entertainment]
  education: [education]
  entertainment: [entertainment]
  film & animation: [entertainment]
  gaming: [games]
  howto & style: [leisure]
  music: [entertainment]
  news & politics: [world]
  nonprofits & activism: [nonprofits]
  people & blogs: [stories]
  pets & animals: [animals]
  science & technology: [technology]
  sports: [sports]
  travel & events: [leisure]


#Facebook
facebook:
  actor/director: [entertainment]
  aerospace/defense: [technology]
  airport: [places]
  album: [entertainment]
  amateur sports team: [sports]
  app: [technology]
  appliances: [products]
  application: [technology]
  artist: [entertainment]
  arts/entertainment/nightlife: [entertainment]
  athlete: [sports]
  attractions/things to do: [leisure]
  author: [books]
  automobiles and parts: [automobiles]
  automotive: [automobile]
  baby goods/kids goods: [products]
  bags/luggage: [products]
  bank/financial institution: [business]
  bank/financial services: [business]
  bar: [food]
  biotechnology: [technology]
  book: [books]
  book store: [books]
  building materials: [products]
  business person: [business]
  business services: [business]
  camera/photo: [technology]
  cars: [automobiles]
  cause: [nonprofits]
  chef: [food]
  chemicals: [technology]
  church/religious organization: [world]
  clothing: [leisure]
  club: [leisure]
  coach: [sports]
  comedian: [entertainment]
  commercial equipment: [products]
  community organization: [world]
  community/government: [world]
  company: [business]
  computers: [technology]
  computers/technology: [technology]
  concert tour: [leisure]
  concert venue: [places]
  consulting/business services: [business]
  dancer: [entertainment]
  doctor: [health]
  drugs: [health]
  editor: [books]
  education: [education]
  electronics: [technology]
  energy/utility: [business]
  engineering/construction: [business]
  entertainer: [entertainment]
  event planning/Event services: [business]
  farming/agriculture: [business]
  field of study: [education]
  fictional character: [games]
  food/beverages: [food]
  food/grocery: [food]
  furniture: [products]
  games/toys: [games]
  government official: [world]
  government organization: [world]
  health/beauty: [health]
  health/medical/pharmacy: [health]
  home decor: [home]
  home improvement: [home]
  hospital/clinic: [health]
  hotel: [leisure]
  household supplies: [home]
  industrials: [business]
  insurance company: [business]
  internet/software: [technology]
  jewelry/watches: [leisure]
  journalist: [world]
  kitchen/cooking: [food]
  landmark: [places]
  lawyer: [world]
  legal/law: [world]
  library: [books]
  local business: [business]
  magazine: [books]
  media/news/publishing: [books]
  mining/Materials: [business]
  monarch: [world]
  movie: [entertainment]
  movie theater: [entertainment]
  movie theater: [entertainment]
  movies/music: [entertainment]
  museum/art gallery: [arts]
  music award: [entertainment]
  music chart: [entertainment]
  music video: [entertainment]
  musical instrument: [entertainment]
  musician/band: [entertainment]
  news personality: [world]
  non-governmental organization (NGO): [nonprofits]
  non-profit organization: [nonprofits]
  office supplies: [business]
  organization: [business]
  outdoor gear/sporting goods: [sports]
  patio/garden: [place]
  pet services: [animals]
  pet supplies: [animals]
  playlist: [entertainment]
  political party: [world]
  political organization: [world]
  politician: [world]
  producer: [business]
  product/service: [business]
  professional services: [business]
  professional sports team: [sports]
  public figure: [world]
  public places: [places]
  radio station: [entertainment]
  real estate: [business]
  record label: [entertainment]
  restaurant/cafe: [food]
  retail and consumer merchandise: [business]
  school: [education]
  school sports team: [sports]
  school: [education]
  shopping/retail: [business]
  small business: [business]
  software: [technology]
  song: [entertainment]
  spas/beauty/personal care: [leisure]
  sports league: [sports]
  sports venue: [sports]
  sports venue: [sports]
  sports/recreation/activities: [sports]
  studio: [entertainment]
  teacher: [education]
  telecommunication: [technology]
  tools/equipment: [business]
  tours/sightseeing: [leisure]
  transit stop: [business]
  transport/freight: [business]
  transportation: [business]
  travel/leisure: [leisure]
  tv: [entertainment]
  tv channel: [enteratinment]
  tv network: [entertainment]
  tv show: [entertainment]
  tv/movie award: [entertainment]
  university: [education]
  vitamins/supplements: [health]
  website: [technology]
  wine/spirits: [food]
  writer: [books]
