#Alchemy Api
alchemyapi:
  arts_entertainment: [entertainment]
  business: [business]
  computer_internet: [technology]
  science_technology: [technology]
  culture_politics: [world]
  gaming: [games]
  health: [health]
  law_crime: [world]
  religion: [world]
  recreation: [leisure]
  sports: [sports]
  weather: [places]
  unknown: [stories]

#OpenCalais
opencalais:
  business_finance: [business]
  disaster_accident: [world]
  education: [education]
  entertainment_culture: [entertainment]
  environment: [world]
  health_medical_pharma: [health]
  hospitality_recreation: [leisure]
  human_interest: [stories]
  labor: [world]
  law_crime: [world]
  politics: [world]
  social_issues: [world]
  religion_belief: [world]
  war_conflict: [world]
  technology_internet: [technology]
  weather: [places]
  sports: [sports]
  other: [stories]


#Youtube
youtube:
  autos & vehicles: [automobiles]
  comedy: [entertainment]
  education: [education]
  entertainment: [entertainment]
  film & animation: [entertainment]
  gaming: [games]
  howto & style: [leisure]
  music: [entertainment]
  news & politics: [world]
  nonprofits & activism: [nonprofits]
  people & blogs: [stories]
  pets & animals: [animals]
  science & technology: [technology]
  sports: [sports]
  travel & events: [places]


#Facebook
facebook:
  song: [entertainment]
  movie: [entertainment]
  website: [technology]
  games: [games]
  products: [products]
  athlete: [sports]
  musician: [entertainment]
  music: [entertainment]
  tv show: [entertainment]
  tv: [entertainment]
  book: [books]
  company: [business]
  Retail and consumer merchandise: [business]

