services_icon_base_path: /images/actwitty/refactor/aw_sketch/sources/
services:
  twitter:
    name: Twitter
    description: Microblogging platform
    active_icon: twitter_active.png
    inactive_icon: twitter_inactive.png       
    enabled: true
  facebook:
    name: Facebook
    description: General purpose social network
    active_icon: facebook_active.png
    inactive_icon: facebook_inactive.png
    enabled: true
  linked_in:
    name: LinkedIn
    description: Professional network
    active_icon: linked_in_active.png
    inactive_icon: linked_in_inactive.png
    enabled: false
  googleplus:
    name: Google+
    description: Social networking platform
    active_icon: google_plus_inactive.png
    inactive_icon: google_plus_inactive.png
    enabled: false
  youtube:
    name: Youtube
    description: Video sharing platform
    active_icon: youtube_active.png
    inactive_icon: youtube_inactive.png
    enabled: false
  github:
    name: Github 
    description: Social Coding Platform
    active_icon: github_active.png
    inactive_icon: github_inactive.png
    enabled: false
  tumblr:
    name: Tumblr
    description: Microblogging platform
    active_icon: tumblr_active.png
    inactive_icon: tumblr_inactive.png
    enabled: false
  foodspotting:
    name: FoodSpotting
    description: Foodie platform
    active_icon: foodspotting_inactive.png
    inactive_icon: foodspotting_inactive.png
    enabled: false
  posterous:
    name: Posterous
    description: Blogging Platform
    active_icon: posterous_inactive.png
    inactive_icon: posterous_inactive.png
    enabled: false
  stackoverflow:
    name: StackOverflow 
    description: Technical discussion forum
    active_icon: stackoverflow_inactive.png
    inactive_icon: stackoverflow_inactive.png
    enabled: false
