title:                   [ 
                            'meta[property="og:title"]',
                            'title',
                            'meta[name="title"]',
                            '#pname a',                                                       # Google Code style
                            '.entryheader h1',                                                # Ruby Inside/Kubrick
                            '.entry-title a',                                                 # Common Blogger/Blogspot rules
                            '.post-title a',
                            '.post_title a',
                            '.posttitle a',
                            '.post-header h1',
                            '.post-title',
                            '.post h1',
                            '.post h3 a',
                            'a.datitle',                                                       # Slashdot style
                            '.posttitle',
                            '.post_title',
                            '.pageTitle',
                            '#main h1.title',
                            '.title h1',                          
                            '.post h2',
                            'h2.title',
                            '.entry h2 a',
                            '.entry h2',                                                      # Common style
                            '.boite_titre a',
                            'h1.headermain',
                            'h1.title',
                            '.mxb h1',                                                        # BBC News
                            '#content h1',
                            '#content h2',
                            '#content h3',
                            'a[rel="bookmark"]',
                            '.products h2',
                            '.caption h3',
                            '#main h2',
                            '#body h1',
                            '#wrapper h1',
                            '#page h1',
                            '.asset-header h1',
                            '#body_content h2'
                        ]

author_name:            [
                          'meta[property="og:author"]',
                          '.author a',
                          '.author',
                          '.post-author .fn',
                          '.wire_author',
                          '.cnnByline b',
                          '.editorlink',
                          '.authors p',
                          'meta[name="author"]',                                            # Traditional meta tag style
                          'meta[name="Author"]',                                            # CNN style
                          'meta[name="AUTHOR"]',                                             # CNN style
                          '.byline a',                                                      # Ruby Inside style
                          '.byline',
                          '.post_subheader_left a',                                         # TechCrunch style
                          '.byl',                                                           # BBC News style
                          '.articledata .author a',
                          '#owners a',                                                      # Google Code style
                          '.auth a',
                          '.auth',
                          '.cT-storyDetails h5',                                            # smh.com.au - worth dropping maybe..
                          'meta[name="byl"]',
                          '.timestamp a',
                          '.fn a',
                          '.fn',
                          '.byline-author',
                          '.ArticleAuthor a',
                          '.blog_meta a',
                          'cite a',
                          'cite',
                          '.contributor_details h4 a',
                          '.meta a'
                       ]


favicon:               [
                          'link[rel="apple-touch-icon"]',      
                          'link[rel="fluid-icon"]',      # Get a Fluid icon if possible..
                          'link[rel="shortcut icon"]',
                          'link[rel="icon"]'
                       ]

description:           [
                          'meta[property="og:description"]',
                          'meta[name="description"]', 
                          'meta[name="Description"]',
                          'meta[name="DESCRIPTION"]',
                          'rdf:Description[name="dc:description"]',
                          '.description'
                       ]
image_url:
                       [
                          'meta[property="og:image"]',
                          'link[rel="image_src"]' 
                       ]

url:                   [
                          'meta[property="og:url"]',
                          'meta[name="url"]',
                          'meta[name="Url"]',
                          'meta[name="URL"]'
                       ]

feed:                  [
                         ['link[@type="application/rss+xml"]', 'lambda { |el| el.attr("href") }'],
                         ['link[@type="application/atom+xml"]', 'lambda { |el| el.attr("href") }']
                       ]
